consumer_key = 'consumer_key'
consumer_secret = 'consumer_secret'
access_token = 'access_token'
access_token_secret = 'access_token_secret'
bearer_token = 'bearer_token'
newsApi = 'newsApi'
Secure_1PSID = 'Secure_1PSID'
Secure_1PSIDTS = 'Secure_1PSIDTS'
