name: Tweet Bot

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule this workflow to run once a day (adjust the time)

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install tweepy
    - name: Install dependencies
      run: pip install gnewsclient
    - name: Install dependencies
      run: pip install palm
      

    - name: Run the bot
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER__BEARER_TOKEN }}
        PALM_API_KEY: ${{ secrets.PALM_API_KEY }}
      run: python main.py
